### ISSUE TITLE
Database Backup Script

### ISSUE THREAD

**Issue by ph1lt0r** [ph1lt0r/PA-WoW-Server#1]
**Describe the solution you'd like**
Phil needs to write a DB backup script

**Describe alternatives you've considered**
I could just let the server fail

**Comment by chrisbier** [comment]
Would this do what you want?
https://github.com/todiadiyatmo/bash-backup-rotation-script/blob/master/backup-mysql.sh

**Comment by ph1lt0r** [comment]
Finished up the base backup script. Chris is adding in a cleanup portion of the script
