### ISSUE TITLE
*Ulduar: Thorim Catch 22

### ISSUE THREAD

**Issue by ifeelrobbed** [ph1lt0r/PA-WoW-Server#17]
**Describe the bug**
Mobs continually spawn in the arena, and you have to go through a hallway to get to Thorim to actually start the fight with him. However, if there is no one in the arena, you are insta killed.

![image](https://user-images.githubusercontent.com/67766369/88714988-32673680-d0e3-11ea-9a75-0ca311bf0550.png)

If you don't try and get to Thorim, waves in the arena will spawn indefinitely
Big time Catch 22
Googling, I see Blizz patched out the insta kill once soloing old content in retail became a thing.

**To Reproduce**
1. Go to Thorim encounter
2. Try to run the gauntlet to actually get to him

**Expected behavior**
Not be insta killed as my character can't be in 2 places at once

**Additional context**
They don't think it be like it is but it do.

**Comment by ph1lt0r** [comment]
Spell has been rendered non-deadly. Does one damage now.
