### ISSUE TITLE
*Trial of the Crusader insta-kill prevents obtaining loot

### ISSUE THREAD

**Issue by ifeelrobbed** [ph1lt0r/PA-WoW-Server#19]
**Describe the bug**
Upon killing Anub'arak, You suddenly take ~13k damage. In my googling of wotlk mechanics I see no mention of the ability being anything other than a DoT. Also considering that Anub'arak's last phase is intended to be a DPS raid I don't see how you could possibly survive it.

That wouldn't be so bad, if you could get to the loot.

The issue is, when your enter the instance to ressurect, the arena floor is back (it collapses to get you to Anub'arak) and it is impossible to go back.

**To Reproduce**
1. Go to Trial of the Crusader
2. Defeat Anub'Arak
3. Instantaneously receive massive massive death inducing damage
4. Raid resets, can't get to loot.

**Expected behavior**
Either the damage spike not exist per my research or at the very least, the raid not resetting so that loot is obtainable.

**Screenshots**
Combat log with regular DoT tick, and spike upon killing Anub'arak
![image](https://user-images.githubusercontent.com/67766369/89216959-00494f00-d591-11ea-9cf7-a5b5e30bf5d0.png)

Upon ressurection and seeing the floor has been restored, thus blocking off the loot and those precious precious crusader orbs
![image](https://user-images.githubusercontent.com/67766369/89217036-2242d180-d591-11ea-9a67-fb748c239515.png)

**Additional context**
Phil is a dreamboat

**Comment by ifeelrobbed** [comment]
To add. The strat for phase 3 is to keep your HP as low as you can so that Anub'Arak's health leach doesn't outheal your damage (it's based on % of current health). So the spike on death blow is no bueno.

**Comment by ph1lt0r** [comment]
fuckin FIIIIIIIIIIIIIIIIIIIIIXED!
