### ISSUE TITLE
ICC Gunship Battle: Cross faction

### ISSUE THREAD

**Issue by ifeelrobbed** [ph1lt0r/PA-WoW-Server#20]
**Describe the bug**
The airship that arrives is tied to the faction of the raid leader. All those of different factions cannot participate.

**To Reproduce**
Example from last night.
Raid leader is Horde, rest are Alliance
Only Horde airship arrives
Airship crew is hostile to Alliance raid members
Alliance raid members cant attack "enemy" airship mobs

**Expected behavior**
Not sure how you'd fix other than just amping the cannon damage so the enemy can just be blasted down as Alliance raid members could use cannons.

**Screenshots**

**Additional context**
I want to go on an airship ride with Phil.

**Comment by ph1lt0r** [comment]
Sadly this can't be fixed even with a module. :(
