### ISSUE TITLE
ICC Gunship Battle: Solo

### ISSUE THREAD

**Issue by ifeelrobbed** [ph1lt0r/PA-WoW-Server#21]
**Describe the bug**
It is not possible for one cannon to outdamage the enemy ship, even if you could stay on the cannon 100% of the time. Cannon does not scale with gear either.

**To Reproduce**
Start airship battle
Be outdamaged by enemy cannons

**Expected behavior**
Again, the only solution I see is to amp cannon damage for player.

**Screenshots**

**Additional context**
Phil really loads my cannon.

**Comment by ph1lt0r** [comment]
FUCKIN FIIIIIIIXED!
