### ISSUE TITLE
Upscaling offset doesn't seem to have taken effect

### ISSUE THREAD

**Issue by ifeelrobbed** [ph1lt0r/PA-WoW-Server#22]
**Describe the bug**
AutoBalance.levelLowerOffset was set to 3 I believe. This should upscale old content up to 77 as an 80 but that doesn't seem to be the case. I know I've seen multiple posts online about setting it to 80 to disable upscaling entirely so it's got to work.

**To Reproduce**
Go to old content like ZG or Magister's Terrace at 80
See that mobs are scaled up to 80.

**Expected behavior**
Mobs upscale to 77 with the above config set to 3

**Screenshots**
![image](https://user-images.githubusercontent.com/67766369/89738307-1cd80200-da3d-11ea-9302-771118289d31.png)

**Additional context**
I just died in Phil's arms tonight. Must've been somethin' he said.

**Comment by ph1lt0r** [comment]
I feel like upscaling is now in a happy place. This can be reopened if we run into more issues.
