### ISSUE TITLE
ICC: Blood-Queen Lana'thel Mind Control

### ISSUE THREAD

**Issue by ifeelrobbed** [ph1lt0r/PA-WoW-Server#24]
**Describe the bug**
This boss's mechanic is to turn the party to vampires. Those turned eventually have to bite a party member or they become mind controlled. The problem is, when running in a small group, you run out of people to bite before you can come close to beating her.

However, the vampirism effect needs to be retained to make this achievement possible (part of granting a rare and very sick mount):
https://www.wowhead.com/achievement=4618/once-bitten-twice-shy-25-player#criteria-of:0+1+2

**Expected behavior**
Works just fine with a full group I would imagine, but the nature of the server and it's population prevent such a scenario from occurring. Perhaps remove the mind control ability? Linked below.

**Screenshots**

**Additional context**

https://www.wowhead.com/npc=37955/blood-queen-lanathel#drops:mode=n10:0+17-20+1
https://www.wowhead.com/spell=70923/uncontrollable-frenzy

**Comment by ph1lt0r** [comment]
Removed mind control effect from her.
