### ISSUE TITLE
Razorgore won’t go below 1hp

### ISSUE THREAD

**Issue by generalorion** [ph1lt0r/PA-WoW-Server#27]
**Describe the bug**
Razorgore, the first boss of Black Wing Lair will not go below 1hp. 

**To Reproduce**
Go to Black Wing Lair and engage Razorgore, the first boss. When his HP reaches 1, it will not go any lower. 

**Expected behavior**
Razorgore to reach 0hp and the portcullis to open allowing access to the rest of the raid. 

**Screenshots**

**Additional context**

**Comment by ph1lt0r** [comment]
I think this should be fixed now. Will close on confirmation

**Comment by ph1lt0r** [comment]
Fixed!
