### ISSUE TITLE
Hellfire Citadel: Shattered Halls - Grand Warlock Nethecurse never actually fights, can't proceed in dungeon

### ISSUE THREAD

**Issue by ifeelrobbed** [ph1lt0r/PA-WoW-Server#9]
**Describe the bug**
Kill his 4 peons and he does his dialog, but never actually flags as attackable.

**To Reproduce**
Go to room 2
![image](https://user-images.githubusercontent.com/67766369/86992212-9cd12a80-c166-11ea-881f-18a19c597d1c.png)

**Expected behavior**

**Screenshots**
Group photo shoot
![image](https://user-images.githubusercontent.com/67766369/86992158-7f9c5c00-c166-11ea-90e5-a7fd757a8ca0.png)

Dialog firing:
![image](https://user-images.githubusercontent.com/67766369/86992181-8dea7800-c166-11ea-81f2-c43bbc41a061.png)

**Additional context**
Character crying because this doesn't unlock until after the fight
![image](https://user-images.githubusercontent.com/67766369/86992291-cdb15f80-c166-11ea-99ef-c352f396dd97.png)

**Comment by linol-shadowcat** [comment]
Found this PR - https://github.com/azerothcore/azerothcore-wotlk/pull/2507
Can you tell if that is in the current build?

**Comment by chrisbier** [comment]
Looks like the fix is from Dec, so it should be in the current build.

**Comment by DrWeggs** [comment]
That room successfully went as expected for me two days ago. Fought Nethercurse, doors opened.

**Comment by ph1lt0r** [comment]
Fixed, if you kill the peons too fast, it won't trigger the script. Logging a ticket to the creator
